# Generated by Django 5.1.6 on 2025-11-14 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_employees_present', models.IntegerField(default=0)),
                ('total_helmet_violations', models.IntegerField(default=0)),
                ('total_loitering_alerts', models.IntegerField(default=0)),
                ('total_items_produced', models.IntegerField(default=0)),
                ('average_compliance_rate', models.FloatField(default=0.0)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_reports',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='daily_repor_date_2e2c97_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('photo_path', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['employee_id'], name='employees_employe_0b5eb0_idx'), models.Index(fields=['first_name'], name='employees_first_n_74bb96_idx')],
            },
        ),
        migrations.CreateModel(
            name='HelmetDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_people', models.IntegerField(default=0)),
                ('compliant_count', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('frame_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'helmet_detection',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='helmet_dete_timesta_431288_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoiteringDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('active_groups', models.IntegerField(default=0)),
                ('group_details', models.JSONField(blank=True, null=True)),
                ('alert_triggered', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'loitering_detection',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='loitering_d_timesta_00cf64_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item_count', models.IntegerField(default=0)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('box_type', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_counter',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='production__timesta_a3328c_idx'), models.Index(fields=['session_date'], name='production__session_585b23_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('log_type', models.CharField(choices=[('helmet', 'Helmet Detection'), ('loitering', 'Loitering Detection'), ('production', 'Production Counter'), ('attendance', 'Attendance System'), ('system', 'System Event'), ('error', 'Error')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_logs_timesta_789991_idx'), models.Index(fields=['log_type'], name='system_logs_log_typ_c8f71a_idx'), models.Index(fields=['severity'], name='system_logs_severit_343258_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='detection_system.employee')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='attendance__timesta_686932_idx'), models.Index(fields=['date'], name='attendance__date_19baa0_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_6b3da7_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
