# Generated by Django 5.1.6 on 2025-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('helmet_detection', 'Helmet Detection'), ('loitering_detection', 'Loitering Detection'), ('production_counter', 'Production Counter'), ('attendance_system', 'Attendance System')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'db_table': 'module_configuration',
                'ordering': ['module_name'],
                'indexes': [models.Index(fields=['module_name'], name='module_conf_module__c342a2_idx'), models.Index(fields=['is_enabled'], name='module_conf_is_enab_7cb984_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('config_value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'db_table': 'system_configuration',
                'ordering': ['config_key'],
                'indexes': [models.Index(fields=['config_key'], name='system_conf_config__1e23cb_idx')],
            },
        ),
    ]
