# Generated by Django 5.2.8 on 2025-11-23 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=50, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "module_configuration",
                "ordering": ["module_name"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_configuration",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="UnknownAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "unknown_attendance",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="unknown_att_timesta_6ca546_idx"
                    )
                ],
            },
        ),
    ]
