# Generated by Django 5.2.8 on 2025-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection_system", "0002_moduleconfiguration_systemconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("stream_url", models.CharField(max_length=500, unique=True)),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            ("rtsp", "RTSP"),
                            ("http", "HTTP"),
                            ("usb", "USB"),
                            ("other", "Other"),
                        ],
                        default="rtsp",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cameras",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="cameras_name_f257e3_idx"),
                    models.Index(
                        fields=["is_active"], name="cameras_is_acti_92a094_idx"
                    ),
                ],
            },
        ),
    ]
