# Generated by Django 5.2.8 on 2025-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection_system", "0002_moduleconfiguration_systemconfiguration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="photo_path",
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="employees/"),
        ),
    ]
