# Generated by Django 5.2.8 on 2025-11-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection_system", "0003_remove_employee_photo_path_employee_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unknownattendance",
            name="image_path",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="snapshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="attendance/verified/"
            ),
        ),
        migrations.AddField(
            model_name="unknownattendance",
            name="snapshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="attendance/unknown/"
            ),
        ),
    ]
